"""session_history.

Revision ID: ab83ad29acc9
Revises: 8ad73a0e3e3b
Create Date: 2026-09-23 07:27:11.331762

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab83ad29acc9"
down_revision = "8ad73a0e3e3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_attendee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=150), nullable=True),
        sa.Column("moderator", sa.Boolean(), nullable=True),
        sa.Column("joins", sa.DateTime(), nullable=True),
        sa.Column("leaves", sa.DateTime(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["meeting_session.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_attendee")
    # ### end Alembic commands ###
